### ISSUE TITLE
Html bug

### ISSUE THREAD

**Issue by TheRed2399** [wave-studio/WaveJS#1]
OS: Windows 11 x64

When i enter basic html and css, the framework will not display the page i created. no error

**Comment by TheRed2399** [comment]
https://cdn.cloudflare.steamstatic.com/steam/apps/256857267/movie480_vp9.webm?t=1635098741

**Comment by Blocksnmore** [comment]
Please follow our [Issue template](https://github.com/wave-studio/WaveJS/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D) when creating an issue
